apiVersion: v1
kind: Service

metadata:
  name: unit-converter-service

spec:
  type: NodePort

  selector:
    app: unit-converter

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
